### PR TITLE
Adding emmean support

### PR DESCRIPTION
**Pull request by mattansb**
WIP #69

### CODE REVIEW

**Comment by TDJorgensen** [comment]
Hi Mattan, 

Sorry for the delay; I'm sure the pandemic interrupted your life as well. I also had a son last month :-)  

I just made some updates to semTools, some of which are related to R 4.0, and semTools now relies on the latest lavaan 0.6-6.  I am about to merge your PR and make some minor changes:

- add headers to the top of the document with info about who worked on it and when
- no reason to issue a warning about `nested` if they are already setting it `FALSE`, so I'll just move that message to the `.onLoad` splash
- I'm not sure we [should](https://cran.r-project.org/doc/manuals/R-exts.html#Package-structure) add an `examples` subdirectory, but I do like the idea of having an extensive set of examples in a separate file.  I will start a naming convention `ex-*.R` within the R subdirectory, and move your examples there.  I will probably create additional files for `permuteMeasEq()` and `measEq.syntax()` as well, since the .R files get tough to navigate with all the extra lines of `roxygen` comments devoted to the examples.  Thanks for the idea :-)

I'll let you know if I have any other questions, but it looks like it will merge fine, even though you were working with an older `DESCRIPTION` file.  Thank you for the generous work on resolving these issues!  This is an excellent contribution, which I plan to use in my own teaching.

**Comment by mattansb** [comment]
Hey Terrence,

Congrats on you baby boy!

I'm glad to see this merged (will probably use this next time teaching `lavaan`). Please let me know if there's anything else I can do.

Great working with you (:

Mattan

**Comment by TDJorgensen** [comment]
This [response](https://stackoverflow.com/questions/26118091/location-of-files-when-using-example-tag-with-roxygen2) on StackOverflow indicated the `examples` subdirectory is best placed within the `inst` subdirectory, which resolves the CRAN check for nonstandard subdirectory names.  

I also ended up just moving the multiple-group check to `recover_data.lavaan()`, just underneath the `.emlav_test_DV()` call, so the additional arguments in `...` are accessible.  Now the warning only prints if they actually forgot to set the `nesting=` argument with a multigroup model:
```
dots <- list(...)
if (lavInspect(object, 'ngroups') > 1L && !("nesting" %in% names(dots))) warning(...)
```
Just sent it to CRAN, hopefully it goes through.

**Comment by mattansb** [comment]
Yeah, that makes more sense (:

I think that should be

```R
dots <- list(...)
if (lavInspect(object, 'ngroups') > 1L && !("nesting" %in% names(dots) && is.null(dots$nesting))) warning(...)
```

Just in case any other `nesting` values (that is not `NULL`) is passed by the user.

**Comment by TDJorgensen** [comment]
I decided against checking is.null because groups could possibly have models that contain different effects (even different variables, by specifying syntax in blocks). So nested effects still are possible, although I’m sure unlikely in practice.

**Pull request merged**
