### PR TITLE
fix: deal with missing data methods

### PR DESCRIPTION
**Pull request by mattansb**
@TDJorgensen This is a minor fix to make the methods work with missing data methods.

### CODE REVIEW

**Comment by TDJorgensen** [comment]
nice!  You have already tested this in an example with missing data?

**Comment by mattansb** [comment]
Yes, that is how I can across it in the first place 😅

**Comment by TDJorgensen** [comment]
Oh wow, I didn't notice the word "fix" in the description :-)

**Comment by mattansb** [comment]
Great - thanks!

Any idea when this can be expected on CRAN?

**Comment by TDJorgensen** [comment]
I need to fix a major bug in the `probe*()` functions, hopefully in the next week. Then I can send to CRAN.

**Comment by mattansb** [comment]
Thanks!

**Pull request merged**
